### ISSUE TITLE
Unable to start script

### ISSUE THREAD

**Issue by mgundle302** [1vke/Scythe-ShopifyMonitorGUI#1]
This project looks amazing and very simple.  I'm unable to get the script running and working.  Could you possibly provide details or instructions as to the steps required to start the project on a server?  Thank you

**Comment by 1vke** [comment]
> This project looks amazing and very simple.  I'm unable to get the script running and working.  Could you possibly provide details or instructions as to the steps required to start the project on a server?  Thank you

Honestly, I highly advise against using this. It's rather old and just not good.

I am no longer selling my python alternative, and would be happy to give it to you. Please message me on discord (1vcas) and I can send it. The version I will be sending you is my first try at a proper threaded python script, so the logic is weird, nonetheless it works. 

I will be closing this issue now.

**Comment by mgundle302** [comment]
Friend request was sent on discord from me (JMCSlots)
